TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += stanford_sr400_photon_counter.db
DATA += stanford_sr400_photon_counter.proto

#=======================================
include $(TOP)/configure/RULES
